### ISSUE TITLE
Won't compile on Windows using Visual Studio 2019

### ISSUE THREAD

**Issue by Losilof39** [rzeronte/brakeza3d#4]
I tried compile this project on Windows 10, generating the .sln file using cmake (debug mode x86), I've installed all the required library, modified some files because of linking errors but still can't compile. I've got 10k warnings and VS even crashed... Is there any other way to get brakeza3d to compile or maybe I'm doing something wrong?

**Comment by rzeronte** [comment]
Thanks for your interest in brakeza3d. The truth is that I have never tried to compile it on windows, only Mac and Linux. If you can provide some more information, captures, etc. Have you tried running your build in debug mode? and see where it fails?
I am interested in helping you and documenting the build process on Windows. a greeting

**Comment by Losilof39** [comment]
[errors.txt](https://github.com/rzeronte/brakeza3d/files/7201511/errors.txt
[Compile_linking_errors.txt](https://github.com/rzeronte/brakeza3d/files/7201512/Compile_linking_errors.txt)
)

Up above are .txt files with all the errors and warnings (there's some in italians, I tried to switch back my IDE to english but there's some issues.. I'm sorry!)

I'm using VS19, building using Debug x64 mode

Most of the errors come from how headers are included in the .cpp file. For example #include <SDL2/SDL.h>, I tried moving all my sdl files in the SDL2 but it doesnt work. I tried changing it to static linking and adding in VS19 the path to the .h files. Also I found that maybe the solution messed up most of the includes because of relative paths (i.e. "..\..\somefile\header.h"), this also occurs to libraries such as assimp and bullet (I've used the latest version available of each of those).  

Thank you for acknowledging the problem and thank you for your time. Greetings

**Comment by rzeronte** [comment]
Hello Losif39, I have invested a few hours and have managed to compile the project on Windows, but I have had to adapt quite a few parts (pthreads.h .. and some exclusive unix libraries). I need a few more days to find some alternatives and get it to compile fine on both systems. I ask you for your patience, greetings!

For the compilation we only need install all libraries and adjust in CMakeLists.txt the include_directories slot. But  at end, you will need fix pthreads. I has been removed render using threads for test compiling, but I want to keep this feature. Is not as easy than I thought.

**Comment by Losilof39** [comment]
> Hello Losif39, I have invested a few hours and have managed to compile the project on Windows, but I have had to adapt quite a few parts (pthreads.h .. and some exclusive unix libraries). I need a few more days to find some alternatives and get it to compile fine on both systems. I ask you for your patience, greetings!
> 
> For the compilation we only need install all libraries and adjust in CMakeLists.txt the include_directories slot. But  at end, you will need fix pthreads. I has been removed render using threads for test compiling, but I want to keep this feature. Is not as easy than I thought.

Thank you for the response! If you need something I'd gladly help you for supporting the project on Windows.

**Comment by rzeronte** [comment]
Hi Losilof39,

I just wanted to tell you that I'm still working on it

![Captura de pantalla (2)](https://user-images.githubusercontent.com/7849348/135513587-2a80e33e-0a7b-42da-8e12-005cff2f562d.png)

I just need resolve a problem with SDL2 and imgui in windows, where i cant share context between them and rendering are "blinking", but the part of threads are resolved.

I was used MinGw/CLion for avoid fight with POSIX Implementation with pthreads in another compiler. Almost all the code has worked, with minor exceptions. This weekend I gonna push a "windows-branch" for testing with a little instructions what i was doing for make it works. I'll let you know. Thanks for your patient.

This will be the branch if you want to try before i finish of refactor imgui issue.

https://github.com/rzeronte/brakeza3d/tree/RoadToWindows (get on eye on CMakeLists.txt, this is full personalized for my env on windows)
--
(Sorry for my english.)

**Comment by Losilof39** [comment]
Hi rzeronte,

thank you for your repsonse! I'm happy to know you're working on supporting brakeza3d on windows. I'll try to compile the project thru the branch you provided up above. Thank you for your time and work. 

Greetings

(don't worry, my english isn't perfect either and it's good enough to get by)

**Comment by rzeronte** [comment]
@Losilof39 I know it's been a long time!! I was working on windows this months and finally i can make it works! README.md was updated with instructions, tested yesterday, last versions! Sorry!
